name: efishery
description: "Platform Budidaya Ikan Terintegrasi untuk Petani Ikan"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  geolocator: ^14.0.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  http_interceptor: ^2.0.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

# Konfigurasi untuk App Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#0288D1"
    theme_color: "#0288D1"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

# Konfigurasi untuk Splash Screen
flutter_native_splash:
  color: "#0288D1"
  image: assets/images/logo.png
  
  # Android 12+ support
  android_12:
    image: assets/images/logo.png
    color: "#0288D1"
    
  # Web support
  web:
    image: assets/images/logo.png
    color: "#0288D1"